Update For Concourse CI
Improwised/frappe_docker pull request #73
Opened 2023-04-24 10:19 UTC by aniketgohelimp

Updated Dockerfile for errpnext and frapee CI

2023-05-01 11:42 UTC, aniketgohelimp commented
@deltasquare4  review this PR.

2023-05-09 10:52 UTC, munir131 requested changes

2023-05-09 10:52 UTC, munir131 commented on build/frappe_s3_attachment-nginx/Dockerfile
> +USER root
@aniketgohelimp Why do we need root user?

2023-05-09 10:52 UTC, munir131 commented on build/frappe_s3_attachment-worker/Dockerfile
> +# USER frappe
@aniketgohelimp why we moved on root user?

2023-05-25 07:32 UTC, closed without merging